Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.memory = 2048
  end
  config.vm.synced_folder "./salt", "/srv/salt"
  config.vm.synced_folder "./pillar", "/srv/pillar"
  config.disksize.size = '20GB'
  config.vm.provision "shell", inline: "sed -i s_http://archive.ubuntu.com/ubuntu_http://ap-southeast-2.archive.ubuntu.com/ubuntu_ /etc/apt/sources.list"
  config.vm.provision :salt do |salt|
    salt.masterless = true
    salt.minion_config = "salt/resources/minion"
    salt.run_highstate = true
    salt.install_type = "stable"
    salt.version = "2019.2.3"
    salt.verbose = true
    salt.colorize = true
    salt.log_level = "info"
  end
  config.vm.define "node01" do |c|
    c.vm.hostname = "node01"
    c.vm.network "private_network", ip: "192.168.56.11"
  end
  config.vm.define "node02" do |c|
    c.vm.hostname = "node02"
    c.vm.network "private_network", ip: "192.168.56.12"
  end
  config.vm.define "node03" do |c|
    c.vm.hostname = "node03"
    c.vm.network "private_network", ip: "192.168.56.13"
  end
  config.vm.define "control01" do |c|
    c.vm.hostname = "control01"
    c.vm.network "private_network", ip: "192.168.56.10"
  end
end
