version: '3.1'
services:
  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - 2181:2181
  manager:
    image: kafkamanager/kafka-manager:1.3.3.23
    ports:
      - 9000:9000
    environment:
      - ZK_HOSTS=zookeeper:2181
