esJavaOpts: -Xmx256m -Xms256m
resources:
    requests:
        memory: 512m
    limits:
        memory: 512m
persistence:
    enabled: true
volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "local-storage"
    resources:
        requests:
            storage 2Gi
