esJavaOpts: -Xmx256m -Xms256m
resources:
    requests:
      cpu: "1000m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "512Mi"
persistence:
    enabled: true
volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "local-storage"
    resources:
        requests:
            storage: 2Gi
