version: "3.7"
services:
    logstash:
        build: .
        ports:
            - 8080:8080
        volumes:
            - ./pipeline/:/usr/share/logstash/pipeline/
        environment:
            - AWS_ACCESS_KEY_ID=xxx
            - AWS_SECRET_ACCESS_KEY=xxx
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - discovery.type=single-node
    kibana:
        image: docker.elastic.co/kibana/kibana:7.3.2
        ports:
            - 5601:5601
        volumes:
            - ./kibana.yml:/usr/share/kibana/config/kibana.yml
