apiVersion: v1
kind: Namespace
metadata:
  name: helloworld-python-local-v1
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld
  namespace: helloworld-python-local-v1
spec:
  template:
    spec:
      containers:
        - image: dev.local/helloworld-python
          env:
            - name: TARGET
              value: "Python Sample v1"
